services:
  - type: web
    name: finassist
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120 --workers 1 --threads 4 --bind 0.0.0.0:10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
